spring:
  r2dbc:
    username: rinha
    password: 123456
    url: r2dbc:postgresql://netuno:5432/rinha
  jackson:
    locale: en_US
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    time-zone: UTC
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
