spring:
  r2dbc:
    username: ${DB_USER:rinha}
    password: ${DB_PASSWORD:123456}
    url: r2dbc:postgresql://${DB_HOST:netuno}:${DB_PORT:5432}/${DB_NAME:rinha}
    pool:
      initial-size: 50
      max-size: 100
  jackson:
    locale: en_US
    date-format: "yyyy-MM-dd'T'HH:mm:ss"
    time-zone: UTC
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true
      FAIL_ON_UNKNOWN_PROPERTIES: false

server:
  tomcat:
    max-threads: 10
    max-connections: 10
